export const GET_TOP_ANIME = "GET_TOP_ANIME";
export const GET_TOP_MANGA = "GET_TOP_MANGA";
export const GET_ANIME_DETAILS = "GET_ANIME_DETAILS";
export const GET_ANIME_REVIEWS = "GET_ANIME_REVIEWS";
export const SEARCH_ANIME = "SEARCH_ANIME";
export const SEARCH_MANGA = "SEARCH_MANGA";
export const RELATED_ANIME = "RELATED_ANIME";
export const RESET_ANIME_PROPS = "RESET_ANIME_PROPS";
